# Generated by Django 2.2.2 on 2019-06-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0004_auto_20190614_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='bazar.ProductCategory'),
        ),
    ]
