# Generated by Django 2.2.2 on 2019-06-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0006_baskecior'),
    ]

    operations = [
        migrations.AddField(
            model_name='baskecior',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
