# Generated by Django 2.2.2 on 2019-06-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0008_auto_20190614_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baskecior',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
