# Generated by Django 2.2.2 on 2019-06-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
