# Generated by Django 2.2.2 on 2019-06-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0011_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(2, 'PAID'), (1, 'UNPAID')], default=1),
        ),
    ]
