# Generated by Django 2.2.2 on 2019-06-17 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0012_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='basket',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bazar.Baskecior'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
